# Generated by Django 2.0.1 on 2018-01-27 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='paragraph_image',
            field=models.CharField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
    ]
