# Generated by Django 2.0.1 on 2018-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180127_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='general', max_length=200),
        ),
    ]
