# Generated by Django 2.0.1 on 2018-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph_title',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
