# Generated by Django 2.0.1 on 2018-02-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180203_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='para_image', max_length=3000)),
                ('para_images', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph_image',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_main_image',
            field=models.CharField(default='chg', max_length=3000),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.CharField(default='chg2', max_length=3000),
        ),
        migrations.AddField(
            model_name='paragraphimage',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Paragraph'),
        ),
    ]
