# Generated by Django 2.0.1 on 2018-02-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180206_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=3000)),
                ('video_link', models.CharField(max_length=3000)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Paragraph')),
            ],
        ),
    ]
