# Generated by Django 2.0.1 on 2018-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_myvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_up_main_image',
            field=models.ImageField(default='image', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_main_image',
            field=models.CharField(blank=True, default='chg', max_length=3000, null=True),
        ),
    ]
