# Generated by Django 2.0.1 on 2018-02-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180206_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='paragraph_up_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='paragraph_video_link',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
